<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1BxHnBa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1BxHnBa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1BxHnBa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1BxHnBa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1BxHnBa\App_KernelDevDebugContainer([
    'container.build_hash' => '1BxHnBa',
    'container.build_id' => '66ec99f9',
    'container.build_time' => 1607903708,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1BxHnBa');
