<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container1BxHnBa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1BxHnBa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1BxHnBa.legacy');
=======
if (\class_exists(\Container5MgWnB6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5MgWnB6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5MgWnB6.legacy');
>>>>>>> b9a4e0ad733485631e13b8284b095958b2041403

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container1BxHnBa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1BxHnBa\App_KernelDevDebugContainer([
    'container.build_hash' => '1BxHnBa',
    'container.build_id' => '66ec99f9',
    'container.build_time' => 1607903708,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1BxHnBa');
=======
    \class_alias(\Container5MgWnB6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5MgWnB6\App_KernelDevDebugContainer([
    'container.build_hash' => '5MgWnB6',
    'container.build_id' => '863e78bd',
    'container.build_time' => 1607903216,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5MgWnB6');
>>>>>>> b9a4e0ad733485631e13b8284b095958b2041403
