<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8hqZlLX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8hqZlLX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8hqZlLX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8hqZlLX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8hqZlLX\App_KernelDevDebugContainer([
    'container.build_hash' => '8hqZlLX',
    'container.build_id' => '5c2223c8',
    'container.build_time' => 1607912105,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8hqZlLX');
