<?php

namespace ContainerGKU5knk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TG0sJSQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TG0sJSQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TG0sJSQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::usersList' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\BlogController::AMProduit' => ['privates', '.service_locator.ZANFrYY', 'get_ServiceLocator_ZANFrYYService', true],
            'App\\Controller\\PanierController::add' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\PanierController::index' => ['privates', '.service_locator.zoY61_S', 'get_ServiceLocator_ZoY61SService', true],
            'App\\Controller\\PanierController::remove' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\SecurityController::inscription' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:usersList' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\BlogController:AMProduit' => ['privates', '.service_locator.ZANFrYY', 'get_ServiceLocator_ZANFrYYService', true],
            'App\\Controller\\PanierController:add' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\PanierController:index' => ['privates', '.service_locator.zoY61_S', 'get_ServiceLocator_ZoY61SService', true],
            'App\\Controller\\PanierController:remove' => ['privates', '.service_locator.h9bDyFt', 'get_ServiceLocator_H9bDyFtService', true],
            'App\\Controller\\SecurityController:inscription' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::usersList' => '?',
            'App\\Controller\\BlogController::AMProduit' => '?',
            'App\\Controller\\PanierController::add' => '?',
            'App\\Controller\\PanierController::index' => '?',
            'App\\Controller\\PanierController::remove' => '?',
            'App\\Controller\\SecurityController::inscription' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:usersList' => '?',
            'App\\Controller\\BlogController:AMProduit' => '?',
            'App\\Controller\\PanierController:add' => '?',
            'App\\Controller\\PanierController:index' => '?',
            'App\\Controller\\PanierController:remove' => '?',
            'App\\Controller\\SecurityController:inscription' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
